### PR TITLE
Remove fastboot binaries

### LINKED ISSUE #1: Should we remove fastboot binaries?
The fastboot files are no longer listed in [adb.json](https://github.com/mozilla/devtools-adb-extension/blob/master/adb.json). Should they be removed from this repository?

I can't see any code to support fastboot in https://bugzilla.mozilla.org/show_bug.cgi?id=1469054 so I assume we are removing the support for this feature?

### PR DESCRIPTION
**Pull request by juliandescottes**
This PR removes fastboot binaries as well as all references to fastboot files. Fixes #1

### CODE REVIEW

**Comment by juliandescottes** [comment]
cc @birtles @hiikezoe 

I can't ask for review or edit project settings :)

**Comment by birtles** [comment]
> I can't ask for review or edit project settings :)

Looks like I sent the invite to @jdescottes instead ;)

You should be added now.

**Comment by juliandescottes** [comment]
Uh! I wonder if I am the one who created this account by mistake. I guess I am not the only jdescottes in the whole world :) 

Thanks for the access!

**Comment by jdescottes** [comment]
No you're not @juliandescottes :-)

**Pull request merged**
