### PR TITLE
Update universal binary

### PR DESCRIPTION
**Pull request by juliandescottes**
Needed to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1780391 

cc @ochameau

### CODE REVIEW

**Comment by ochameau** [comment]
I have no way to test on mac but I verified that was official binaries from android.
It would be nice to mention, at least in the changeset title, that this is version r33.0.2.

Also, I'm wondering if we should update all platforms instead of introducing the very lastest only for MacOS?

**Review by ochameau — APPROVED** [review]
It looks good to me, thanks for jumping on this!

It would be nice to tag the changeset once the xpi is released:
https://github.com/mozilla/devtools-adb-extension/tags
And then bump the version to 0.0.7pre on `master`.

**Comment by juliandescottes** [comment]
All good points! Thanks for the feedback, I'll try to update the other binaries at the same time and will mention r33.0.2 in the commit message.

**Comment by juliandescottes** [comment]
One thing to consider is that the new binaries are much bigger than the old ones:
mac: 13.7 MB (was 2)
win: 6 MB (was 1.5)
linux64: 8.1 MB (was 2.2)  

This results in bigger xpi files:
mac: 5.7 MB (was 778 kB)
win: 2.9 MB (was 712 kB)
linux64: 3.2 MB (was 821 KB)

So 4 to 8 times bigger depending on the OS. I'm not sure we have a lot of options to avoid that (at least for mac). Knowing that we don't show any progress indicator when installing the addon via about:debugging, the increase in size might lead to UX issues.

**Comment by mstange** [comment]
I think fixing https://bugzilla.mozilla.org/show_bug.cgi?id=1780391 is important enough that it outweighs the load time increase.

**Comment by juliandescottes** [comment]
Rebased the PR.

Updated the binaries to 35.0.1, retrieved from:
- https://dl.google.com/android/repository/platform-tools-latest-darwin.zip
- https://dl.google.com/android/repository/platform-tools-latest-linux.zip
- https://dl.google.com/android/repository/platform-tools-latest-windows.zip

I could not find a linux32 version (same as for the previous version of this PR)

**Comment by juliandescottes** [comment]
I tested the extension built locally on macos, and I can install it via about:debugging without getting any warning from the system.

FWIW, to test locally I am usually doing the following:
- run Firefox with a clean profile
- make sure adb is killed
- in about:config update:
  - update devtools.remote.adb.extensionURL to point to the file:/// url for the locally built extension
  - update xpinstall.signatures.required to `false`

**Comment by juliandescottes** [comment]
cc @willdurand can you take a look and check if I forgot anything for the Github part?

**Review by willdurand — APPROVED** [review]
This looks good to me, thanks!

**Pull request merged**
